export const SIGNIN_TEST_ID = {
  EMAIL_INPUT: 'EMAIL_INPUT',
  PW_INPUT: 'PASSWORD_INPUT',
  EYE_SLASHED_BUTTON: 'CLOSED_EYE_ICON',
  EYE_OPENED_BUTTON: 'OPENED_EYE_ICON',
  INPUT_RESET_BUTTON: 'INPUT_X_ICON',
  LOGIN_BUTTON: 'FORM_LOGIN_BUTTIN',
} as const;
